
using System.Text;
using System.Text.RegularExpressions;

GenerateDelegates("../OpenTK/Graphics/OpenGL/GLDelegates.cs", GetCoreFunctions("../OpenTK/Graphics/OpenGL/GLCore.cs"));

GenerateDelegates("../OpenTK/Graphics/ES20/Delegates.cs", GetCoreFunctions("../OpenTK/Graphics/ES20/Core.cs"));

string OutputName(string input) => Path.ChangeExtension(input, ".g.cs");

HashSet<string> GetCoreFunctions(string sourceFile)
{
    var lines = File.ReadAllLines(sourceFile).Select(x => x.Replace("\t", " ")).ToArray();
    var res = new HashSet<string>();

    var rx = new Regex(@"\s([a-zA-Z0-9_]+)\(.*\);\s*$");
    foreach (var line in lines)
    {
        if (line.Contains(" extern ") && rx.Match(line) is { Success: true } match)
        {
            res.Add(match.Groups[1].Value);
        }
    }

    return res;
}

void GenerateDelegates(string sourceFile, HashSet<string> coreFunctions, string? writeFile = null)
{
    writeFile ??= OutputName(sourceFile);

    var lines = File.ReadAllLines(sourceFile).Select(x => x.Replace("\t", " ")).ToArray();
    var ns = lines.First(x => x.StartsWith("namespace ")).Replace("{", "").Split(" ").Last();
    var clsDefs = lines.First(x => x.Contains("partial class ")).Replace("{", "").Trim();

    var rx = new Regex(@".*\s+(.*?)\s+(.*?);");
    List<string> delegates = new();
    foreach (var line in lines)
    {
        if (line.Contains(" internal ") && line.Contains(" static ") && !line.Contains(" class "))
        {
            var match = rx.Match(line);
            delegates.Add($"{match.Groups[1].Value} {match.Groups[2].Value}");
        }
    }

    StringBuilder sb = new StringBuilder();
    sb.AppendLine($"// Auto generated by ReflectionGenerator");
    sb.AppendLine($"namespace {ns} {{");
    sb.AppendLine($"{clsDefs} {{");
    sb.AppendLine("protected override unsafe void LoadExtensionSetters() {");
    sb.AppendLine("DelegateSetters = new() {");
    foreach (var del in delegates)
    {
        var parts = del.Split(" ");
        var type = parts[0];
        var name = parts[1];
        if (coreFunctions.Contains(name))
            sb.AppendLine($"{{\"{name}\", new(Make<Delegates.{type}>, d => Delegates.{name} = (Delegates.{type})d, () => Delegates.{name} = Core.{name})}},");
        else
            sb.AppendLine($"{{\"{name}\", new(Make<Delegates.{type}>, d => Delegates.{name} = (Delegates.{type})d)}},");
    }
    sb.AppendLine("};");
    sb.AppendLine("}");
    sb.AppendLine("}");
    sb.AppendLine("}");

    File.WriteAllText(writeFile, sb.ToString());
}